language: php

sudo: false

git:
    depth: 1

cache:
    directories:
        - $HOME/.composer

env:
    global:
        - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-progress --optimize-autoloader"
        - COLLECT_COVERAGE=0

jobs:
  include:
    -
        stage: Static Code Analysis
        php: nightly
        install:
            - composer global require $DEFAULT_COMPOSER_FLAGS phpmd/phpmd:^2.4.3 mi-schi/phpmd-extension:^4.2
        before_script:
            - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then COMMIT_RANGE=$TRAVIS_COMMIT_RANGE; else COMMIT_RANGE="HEAD~..HEAD"; fi;
            - export COMMIT_SCA_FILES=`git diff --name-only --diff-filter=ACMRTUXB $COMMIT_RANGE`
        script:
            - ./check_trailing_spaces.sh || travis_terminate 1
            # TODO - if [ -n "$COMMIT_SCA_FILES" ]; then $HOME/.composer/vendor/bin/phpmd `echo $COMMIT_SCA_FILES | sed 's/ /,/g'` text phpmd.xml --exclude src/Resources,tests/Fixtures; fi

    -
        stage: Test
        php: 7.1
        env: COLLECT_COVERAGE=1
        before_script:
            # check phpdbg
            - phpdbg --version 2> /dev/null || { echo 'No phpdbg'; export COLLECT_COVERAGE=0; }

            # for building a tag release we don't need to collect code coverage
            - if [ $TRAVIS_TAG ]; then export COLLECT_COVERAGE=0; fi
        script:
            - if [ $COLLECT_COVERAGE == 0 ]; then vendor/bin/phpunit --verbose || travis_terminate 1; fi
            - if [ $COLLECT_COVERAGE == 1 ]; then phpdbg -qrr vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml || travis_terminate 1; fi
            - php php-cs-fixer --diff --dry-run -v fix || travis_terminate 1
            - if [ $COLLECT_COVERAGE == 1 ]; then php vendor/bin/coveralls -v; fi

    -
        stage: Tests
        php: nightly
        env: COMPOSER_FLAGS="--ignore-platform-reqs" SYMFONY_DEPRECATIONS_HELPER=weak PHP_CS_FIXER_IGNORE_ENV=1
        script:
            - php php-cs-fixer fix --rules @PHP70Migration:risky,@PHP71Migration,native_function_invocation -q || travis_terminate 1
            - vendor/bin/phpunit --verbose || travis_terminate 1
            - git checkout . -q
            - php php-cs-fixer --diff --dry-run -v fix

    -
        stage: Tests
        php: 5.6
        env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        script:
            - vendor/bin/phpunit --verbose || travis_terminate 1
            - php php-cs-fixer --diff --dry-run -v fix

    -
        stage: Tests
        php: 7.0
        script:
            - vendor/bin/phpunit --verbose || travis_terminate 1
            - php php-cs-fixer --diff --dry-run -v fix

    -
        stage: Tests
        php: hhvm
        env: SKIP_LINT_TEST_CASES=1
        sudo: required
        dist: trusty
        group: edge
        script:
            - vendor/bin/phpunit --verbose || travis_terminate 1
            - php php-cs-fixer --diff --dry-run -v fix

    -
        stage: Deployment
        php: 7.1
        script: echo "Deploying to GitHub releases ..."
        before_deploy:
            # install box2
            - curl -LSs http://box-project.github.io/box2/installer.php | php
            - php box.phar --version

            # ensure that deps will work on lowest supported PHP version
            - composer config platform.php 2> /dev/null || composer config platform.php 5.6.0

            # require suggested packages
            - composer require --no-update symfony/polyfill-mbstring

            # update deps to highest possible for lowest supported PHP version
            - composer update $DEFAULT_COMPOSER_FLAGS --no-dev --prefer-stable

            - composer info -D | sort

            # build phar file
            - php -d phar.readonly=false box.phar build
        deploy:
            provider: releases
            api_key:
                secure: K9NKi7X1OPz898fxtVc1RfWrSI+4hTFFYOik932wTz1jC4dQJ64Khh1LV9frA1+JiDS3+R6TvmQtpzbkX3y4L75UrSnP1ADH5wfMYIVmydG3ZjTMo8SWQWHmRMh3ORAKTMMpjl4Q7EkRkLp6RncKe+FAFPP5mgv55mtIMaE4qUk=
            file: php-cs-fixer.phar
            skip_cleanup: true
            on:
                repo: FriendsOfPHP/PHP-CS-Fixer
                tags: true

before_install:
    # turn off XDebug
    - phpenv config-rm xdebug.ini || return 0

    # Composer: boost installation
    - composer global show -ND 2>&1 | grep "hirak/prestissimo" || travis_retry composer global require $DEFAULT_COMPOSER_FLAGS hirak/prestissimo

    # display tasks configuration for a job
    - set | grep ^TASK | sort

install:
    - travis_retry composer update $DEFAULT_COMPOSER_FLAGS $COMPOSER_FLAGS
    - composer info -D | sort
