language: php

sudo: false

git:
    depth: 1

cache:
    directories:
        - $HOME/.composer

env:
    global:
        - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-progress --optimize-autoloader"
        - TASK_TESTS=1
        - TASK_TESTS_COVERAGE=0
        - TASK_CS=1
        - TASK_SCA=0

php:
  - 7.0

jobs:
  include:
    - stage: lint
      script:
        - echo "JOB LINT"
    - stage: test
      script:
        - echo "JOB UTEST"
    - stage: e2e
      script:
        - echo "JOB E2E"

before_deploy:
    # install box2
    - curl -LSs http://box-project.github.io/box2/installer.php | php
    - php box.phar --version

    # ensure that deps will work on lowest supported PHP version
    - composer config platform.php 2> /dev/null || composer config platform.php 5.6.0

    # require suggested packages
    - composer require --no-update symfony/polyfill-mbstring

    # update deps to highest possible for lowest supported PHP version
    - composer update $DEFAULT_COMPOSER_FLAGS --no-dev --prefer-stable

    - composer info -D | sort

    # build phar file
    - php -d phar.readonly=false box.phar build

deploy:
    provider: releases
    api_key:
        secure: K9NKi7X1OPz898fxtVc1RfWrSI+4hTFFYOik932wTz1jC4dQJ64Khh1LV9frA1+JiDS3+R6TvmQtpzbkX3y4L75UrSnP1ADH5wfMYIVmydG3ZjTMo8SWQWHmRMh3ORAKTMMpjl4Q7EkRkLp6RncKe+FAFPP5mgv55mtIMaE4qUk=
    file: php-cs-fixer.phar
    skip_cleanup: true
    on:
        repo: FriendsOfPHP/PHP-CS-Fixer
        tags: true
        condition: $DEPLOY = yes
